### ISSUE TITLE
Homepage Not Scaling to certain screen ratios

### ISSUE THREAD

**Issue by dbrucknr** [tsugicloud/website#1]
Hello Professor Severance,

I noticed the Tsugi cloud website is not scaling for certain screen ratios. There are large white bars of empty space appearing either at the bottom or side of the webpage.

Here is a screenshot of the symptom from my computer:
<img width="2256" alt="Screen Shot 2019-11-14 at 9 27 44 AM" src="https://user-images.githubusercontent.com/46636362/68865572-0d4fa680-06c1-11ea-9c2d-acf7ea273666.png">

I wanted to help fix this issue. I have been able to replicate this issue on mobile devices as well as computer screens set at a 16:9 ratio.

**Comment by csev** [comment]
Derek - thanks for the note.  I really just need to get rid of the entire HTML and rebuild it.  I used a system called Grav to make the site and while it made it quickly and it is pretty - I am stuck with their markup.

/Chuck

**Comment by dbrucknr** [comment]
Hey Professor Severance,

I appreciate your response. I'd really like to contribute to one of your open source projects, so I'll keep looking. Hopefully you'll hear from me again soon.

I hope your semester is going well.

Derek
